config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Homes', 'action' => 'checkDevice']);
    $routes->connect('/about-us', ['controller' => 'Pages', 'action' => 'display','about-us']);
    $routes->connect('/contact-us', ['controller' => 'Pages', 'action' => 'display','contact-us']);
    $routes->connect('/faq', ['controller' => 'Pages', 'action' => 'display','faq']);
    $routes->connect('/what-we-do', ['controller' => 'Pages', 'action' => 'display','what-we-do']);
    $routes->connect('/how-scl-work', ['controller' => 'Pages', 'action' => 'display','how-scl-work']);
    $routes->connect('/poweredby11', ['controller' => 'PoweredByElevens', 'action' => 'index']);


    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
    $routes->connect('/site-under-construction/*', ['controller' => 'Pages', 'action' => 'siteUnderConstruction']);
    $routes->connect('/site-down/*', ['controller' => 'Pages', 'action' => 'siteDown']);
    $routes->connect('/filmDirector-signUp1', ['controller' => 'UserProfiles', 'action' => 'filmDirector','prefix'=>'artist']);
    $routes->connect('/fashionDesigner-signUp', ['controller' => 'Users', 'action' => 'register','prefix'=>'designer']);
    $routes->connect('/fashionDesigner-completeprofile', ['controller' => 'Users', 'action' => 'add','prefix'=>'designer']);
    $routes->connect('/artist-signUp', ['controller' => 'Users', 'action' => 'register','prefix'=>'artist']);
    $routes->connect('/catalog', ['controller' => 'catalogues', 'action' => 'index']);
    $routes->connect('/filmDirector-signUp', ['controller' => 'Users', 'action' => 'register','prefix'=>'director']);
    $routes->connect('/filmDirector-completeprofile', ['controller' => 'Users', 'action' => 'add','prefix'=>'director']);

    $routes->connect('/disable-layout/*', ['controller' => 'ArtistPitchVideos', 'action' => 'disableLayout','prefix' => 'admin']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

Router::prefix('admin', function ($routes) {
    $routes->setExtensions(['json']);
    $routes->connect('/', ['controller' => 'Users', 'action' => 'login']);
    $routes->fallbacks(DashedRoute::class);
});

Router::prefix('artist', function ($routes) {
    $routes->setExtensions(['json']);
    $routes->connect('/login', ['controller' => 'Logins', 'action' => 'add']);
    $routes->connect('/logout', ['controller' => 'Logins', 'action' => 'delete']);
    $routes->connect('/registration', ['controller' => 'Users', 'action' => 'register']);
    $routes->connect('/change-password', ['controller' => 'Logins', 'action' => 'edit']);
    $routes->connect('/about-us', ['controller' => 'Logins', 'action' => 'aboutUs']);
    $routes->fallbacks(DashedRoute::class);
});

Router::prefix('designer', function ($routes) {
    $routes->setExtensions(['json']);
    $routes->fallbacks(DashedRoute::class);
});

Router::prefix('director', function ($routes) {
    $routes->setExtensions(['json']);
    $routes->fallbacks(DashedRoute::class);
});

Router::prefix('influencer', function ($routes) {
    $routes->setExtensions(['json']);
    $routes->fallbacks(DashedRoute::class);
});


Router::prefix('api', function ($routes) {
    $routes->setExtensions(['json']);
    $routes->resources('Users', ['inflect' => 'dasherize']); 
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/User.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\Auth\DefaultPasswordHasher;

/**
 * User Entity
 *
 * @property int $id
 * @property int $role_id
 * @property string $email
 * @property string $password
 * @property int $status
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\Role $role
 * @property \App\Model\Entity\UserProfile[] $user_profiles
 */
class User extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'role_id' => true,
        'email' => true,
        'password' => true,
        'status' => true,
        'created' => true,
        'modified' => true,
        'role' => true,
        'user_profile' => true,
        'user_media_handle' => true,
        'user_records' => true,
        'user_record' => true,
        'user_bank_detail' => true,
        'user_plan' => true,
        'step_completed' => true,
        'user_plans' =>true,
        'fashion_designer_profile' => true,
        'fashion_designer_media_handle' => true,
        'film_director_profile' => true,
        'film_director_media_handle' => true,
        'created_by' => true,
        'level_id' => true,
        'last_login' => true,
        'levels' => true,
        'chat_session_id' => true,
        'influencer_profile' => true,
        'partner_profile' => true,
        'user_supporters' => true,
        
    ];

    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password'
    ];

    protected function _setPassword($password) {
        if (strlen($password) > 0) {
          return (new DefaultPasswordHasher)->hash($password);
        }
    }

    protected function _getFullName() {   
        if(!empty($this->user_profile)) {
            return $this->user_profile->first_name . '  ' . $this->user_profile->last_name;
        }
        return $this->email;
    }
}

src/Controller/Admin/UserProfilesController.php
<?php
namespace App\Controller\Admin;

use App\Controller\AppController;

/**
 * UserProfiles Controller
 *
 * @property \App\Model\Table\UserProfilesTable $UserProfiles
 *
 * @method \App\Model\Entity\UserProfile[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class UserProfilesController extends AppController {

    public function initialize() {
        parent::initialize();
        $this->viewBuilder()->setLayout('admin/admin');
        $this->loadModel('UserRecords');
    }
    
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index()
    {
        $this->paginate = [
            'conditions' => ['UserRecords.user_id' => $this->Auth->user('id')],
            'contain' => ['UserRecordKeys'],
            'limit' => 10
        ];
        $userRecords = $this->paginate($this->UserRecords);
        $this->set(compact('userRecords'));
    }

    /**
     * View method
     *
     * @param string|null $id User Profile id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $userRecords = $this->UserRecords->get($id, [
            'contain' => ['UserRecordKeys']
        ]);

        $this->set('userRecords', $userRecords);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $userProfile = $this->UserRecords->newEntity();
        if ($this->request->is('post')) {
            $data = $this->request->getData();
            $data['user_id'] = $this->Auth->user('id');
            $data = $this->UserRecords->patchEntity($userProfile, $data,['associated' => ['UserRecordKeys']]);
            if ($this->UserRecords->save($data)) {
                $this->Flash->success(__('The Record has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The Record could not be saved. Please, try again.'));
            return $this->redirect(['action' => 'add']);
        }
      /*  $users = $this->UserProfiles->Users->find('list', ['limit' => 200]);
        $genres = $this->UserProfiles->Genres->find('list', ['limit' => 200]);*/
        //$this->set(compact('userProfile', 'users', 'genres'));
    }

    /**
     * Edit method
     *
     * @param string|null $id User Profile id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $userProfile = $this->UserProfiles->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $userProfile = $this->UserProfiles->patchEntity($userProfile, $this->request->getData());
            if ($this->UserProfiles->save($userProfile)) {
                $this->Flash->success(__('The user profile has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The user profile could not be saved. Please, try again.'));
        }
        $users = $this->UserProfiles->Users->find('list', ['limit' => 200]);
        $genres = $this->UserProfiles->Genres->find('list', ['limit' => 200]);
        $this->set(compact('userProfile', 'users', 'genres'));
    }

    /**
     * Delete method
     *
     * @param string|null $id User Profile id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $userProfile = $this->UserProfiles->get($id);
        if ($this->UserProfiles->delete($userProfile)) {
            $this->Flash->success(__('The user profile has been deleted.'));
        } else {
            $this->Flash->error(__('The user profile could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Controller/Artist/ArtistMusicsController.php
<?php
namespace App\Controller\Artist;

use App\Controller\AppController;
use Cake\Datasource\Exception\RecordNotFoundException;

/**
 * ArtistMusics Controller
 *
 * @property \App\Model\Table\ArtistMusicsTable $ArtistMusics
 *
 * @method \App\Model\Entity\ArtistMusic[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ArtistMusicsController extends AppController
{
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['Users']
        ];
        $artistMusics = $this->paginate($this->ArtistMusics);

        $this->set(compact('artistMusics'));
    }

    /**
     * View method
     *
     * @param string|null $id Artist Music id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $artistMusic = $this->ArtistMusics->get($id, [
            'contain' => ['Users']
        ]);

        $this->set('artistMusic', $artistMusic);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add() {
        $this->viewBuilder()->setLayout('/User/artist_dashboard');        
        
        try {
            $artistVideo = $this->ArtistMusics->find()
                ->where([
                    'ArtistMusics.user_id' => $this->Auth->user('id')
                ])
                ->firstOrFail();

        } catch (RecordNotFoundException $e) {
            $artistVideo = $this->ArtistMusics->newEntity();
        } catch(InvalidPrimaryKeyException $e) {
            $artistVideo = $this->ArtistMusics->newEntity();
        }
        
        if ($this->request->is('post')) {

            $userId = $this->Auth->user('id');
            $data = $this->request->getData();
            $data['user_id'] = $userId;
            $artistVideo = $this->ArtistMusics->patchEntity($artistVideo, $data);
            if ($this->ArtistMusics->save($artistVideo)) {
                $this->Flash->success(__('The video has been uploaded successfuly.'));

                return $this->redirect(['action' => 'add']);
            }
            $this->Flash->error(__('The video could not be uploaded. Please, try again.'));           
        
        }
        
        $users = $this->ArtistMusics->Users->find('list', ['limit' => 200]);

        $this->set(compact('users','artistVideo'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Artist Music id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $artistMusic = $this->ArtistMusics->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $artistMusic = $this->ArtistMusics->patchEntity($artistMusic, $this->request->getData());
            if ($this->ArtistMusics->save($artistMusic)) {
                $this->Flash->success(__('The artist music has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The artist music could not be saved. Please, try again.'));
        }
        $users = $this->ArtistMusics->Users->find('list', ['limit' => 200]);
        $this->set(compact('artistMusic', 'users'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Artist Music id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $artistMusic = $this->ArtistMusics->get($id);
        if ($this->ArtistMusics->delete($artistMusic)) {
            $this->Flash->success(__('The artist music has been deleted.'));
        } else {
            $this->Flash->error(__('The artist music could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Artist/UserProfiles/edit.ctp
<div class="col-lg-9">
        <div class="content h-100">

            <?= $this->Form->create($userProfile, ['type' => 'file', 'id' => 'editBiographyForm']) ?>
            <div class="bg-white h-100">
                <div class="cover-img">
                    <?php 
                        $banner = $this->Images->artistBanner($userProfile->user_profile);
                        if($banner) {
                            echo $this->Html->image($banner, ['alt' => 'cover images']);

                        }else {
                            echo $this->Html->image('artist/cover.jpg', ['alt' => 'cover images']);
                        }
                    ?>
                    <div class="choose_file">
                        <span class="d-block">
                            <svg version="1.1" width="24px" height="24px" fill="#fff" x="0px" y="0px"
                                viewBox="0 0 490.667 490.667" style="enable-background:new 0 0 490.667 490.667;"
                                xml:space="preserve">
                                <g>
                                    <g>
                                        <g>
                                            <path
                                                d="M448,128h-67.627l-39.04-42.667H192v64h-64v64H64v213.333c0,23.467,19.2,42.667,42.667,42.667H448
                                           c23.467,0,42.667-19.2,42.667-42.667v-256C490.667,147.2,471.467,128,448,128z M277.333,405.333
                                           c-58.88,0-106.667-47.787-106.667-106.667S218.453,192,277.333,192S384,239.787,384,298.667S336.213,405.333,277.333,405.333z" />
                                            <polygon points="64,192 106.667,192 106.667,128 170.667,128 170.667,85.333 106.667,85.333 106.667,21.333 64,21.333 64,85.333 
                                           0,85.333 0,128 64,128            " />
                                            <path
                                                d="M277.333,230.4c-37.76,0-68.267,30.507-68.267,68.267h0c0,37.76,30.507,68.267,68.267,68.267
                                           c37.76,0,68.267-30.507,68.267-68.267S315.093,230.4,277.333,230.4z" />
                                        </g>
                                    </g>
                            </svg>
                        </span>
                        <?= 
                            $this->Form->file('user_profile.banner', [
                                'type' => 'file', 
                                'required' => false,
                                'accept' =>"image/*",
                                'label' => false
                            ]) 
                        ?>
                    </div>
                    <div class="profile-pic">
                        <?php 
                            $avatar = $this->Images->artistAvatar($userProfile->user_profile); 
                            if($avatar):
                                echo $this->Html->image($avatar, ['class' => 'rounded-circle', 'style' => 'width:120px; height:120px;']);
                        ?>
                        <?php else: ?>
                            <svg version="1.1" x="0px" y="0px" viewBox="0 0 53 53"
                                style="enable-background:new 0 0 53 53;" xml:space="preserve">
                                <path style="fill:#333333;" d="M18.613,41.552l-7.907,4.313c-0.464,0.253-0.881,0.564-1.269,0.903C14.047,50.655,19.998,53,26.5,53
                               c6.454,0,12.367-2.31,16.964-6.144c-0.424-0.358-0.884-0.68-1.394-0.934l-8.467-4.233c-1.094-0.547-1.785-1.665-1.785-2.888v-3.322
                               c0.238-0.271,0.51-0.619,0.801-1.03c1.154-1.63,2.027-3.423,2.632-5.304c1.086-0.335,1.886-1.338,1.886-2.53v-3.546
                               c0-0.78-0.347-1.477-0.886-1.965v-5.126c0,0,1.053-7.977-9.75-7.977s-9.75,7.977-9.75,7.977v5.126
                               c-0.54,0.488-0.886,1.185-0.886,1.965v3.546c0,0.934,0.491,1.756,1.226,2.231c0.886,3.857,3.206,6.633,3.206,6.633v3.24
                               C20.296,39.899,19.65,40.986,18.613,41.552z" />
                                <g>
                                    <path style="fill:#ffffff;"
                                        d="M26.953,0.004C12.32-0.246,0.254,11.414,0.004,26.047C-0.138,34.344,3.56,41.801,9.448,46.76
                                   c0.385-0.336,0.798-0.644,1.257-0.894l7.907-4.313c1.037-0.566,1.683-1.653,1.683-2.835v-3.24c0,0-2.321-2.776-3.206-6.633
                                   c-0.734-0.475-1.226-1.296-1.226-2.231v-3.546c0-0.78,0.347-1.477,0.886-1.965v-5.126c0,0-1.053-7.977,9.75-7.977
                                   s9.75,7.977,9.75,7.977v5.126c0.54,0.488,0.886,1.185,0.886,1.965v3.546c0,1.192-0.8,2.195-1.886,2.53
                                   c-0.605,1.881-1.478,3.674-2.632,5.304c-0.291,0.411-0.563,0.759-0.801,1.03V38.8c0,1.223,0.691,2.342,1.785,2.888l8.467,4.233
                                   c0.508,0.254,0.967,0.575,1.39,0.932c5.71-4.762,9.399-11.882,9.536-19.9C53.246,12.32,41.587,0.254,26.953,0.004z" />
                                </g>
                            </svg>
                        <?php endif; ?>
                        <div class="choose_file upload-profile">
                            <span class="d-block">
                                <svg version="1.1" width="14px" height="14px" x="0px" y="0px"
                                    viewBox="0 0 469.331 469.331"
                                    style="enable-background:new 0 0 469.331 469.331;" xml:space="preserve">
                                    <g>
                                        <path d="M438.931,30.403c-40.4-40.5-106.1-40.5-146.5,0l-268.6,268.5c-2.1,2.1-3.4,4.8-3.8,7.7l-19.9,147.4
c-0.6,4.2,0.9,8.4,3.8,11.3c2.5,2.5,6,4,9.5,4c0.6,0,1.2,0,1.8-0.1l88.8-12c7.4-1,12.6-7.8,11.6-15.2c-1-7.4-7.8-12.6-15.2-11.6
l-71.2,9.6l13.9-102.8l108.2,108.2c2.5,2.5,6,4,9.5,4s7-1.4,9.5-4l268.6-268.5c19.6-19.6,30.4-45.6,30.4-73.3
S458.531,49.903,438.931,30.403z M297.631,63.403l45.1,45.1l-245.1,245.1l-45.1-45.1L297.631,63.403z M160.931,416.803l-44.1-44.1
l245.1-245.1l44.1,44.1L160.931,416.803z M424.831,152.403l-107.9-107.9c13.7-11.3,30.8-17.5,48.8-17.5c20.5,0,39.7,8,54.2,22.4
s22.4,33.7,22.4,54.2C442.331,121.703,436.131,138.703,424.831,152.403z" />
                                    </g>
                                </svg>
                            </span>
                            <?= 
                                $this->Form->control('user_profile.avatar', [
                                    'type' => 'file',
                                    'accept' =>"image/*",
                                    'label' => false
                                ])
                            ?>
                        </div>

                    </div>
                    <div class="profile-name"><?= ucfirst($userProfile->full_name) ?></div>
                </div>
                <div class="p-4">
                    <div class="row">
                        <div class="col-12">
                            <h2 class="tab-title mb-2">Edit Biography</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                                <?= $this->Flash->render();?>
                                <div class="form-group biography mt-3">
                                    <label>Biography</label>
                                    <?= 
                                        $this->Form->control('user_profile.biography', [
                                            'type' => 'textarea',
                                            'class' => 'form-control',
                                            'placeholder' => "Mauris felis risus, luctus lobortis hendrerit eu, tincidunt eget ipsum. Ut suscipit et erat vestibulum aliquam. Cras vehicula viverra aliquet. Nulla facilisi. In lorem arcu, gravida eget elementum in, efficitur at enim. Vestibulum sed mattis dui. Suspendisse vel porta magna.",
                                            'label' => false,
                                            'maxlength' => 300
                                        ]) 
                                    ?>
                                    <small class="text-muted">
                                        300 character limit, plain text only.
                                    </small>
                                </div>
                                <div class="form-group text-right mt-4">
                                    <button type="submit" class="bg-red text-white py-2 px-4"
                                        name="submit">Update</button>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
            <?= $this->Form->end() ?>
        </div>
    </div>
<?php
    echo $this->Html->script([
        'Artist/UserProfiles/edit'
    ], [
        'block' => 'scriptBottom'
    ]);
?>

src/Template/Artist/UserProfiles/page_under_construction.ctp
<div class="col-lg-9">
    <div class="content h-100">
        <div class="bg-white h-100 p-4">
            <div class="row">
                <div class="col-12">
                    <?= $this->Html->image('underconstruction.jpg',['class' => 'img-fluid'])?>
                </div>
            </div>
        </div>
    </div>
</div>

src/Template/Artist/UserProfiles/thanku_page.ctp
<div class="container thankupage">
    <div class="gray-strip">Your registration is complete.</div>

    <p class="text-center mt-5">A Sound Check Live team Member will contact you shortly for on-boarding.</br>
        Your Sound Check live profile has generated a Scl Score of 73.4.</br>
        This is a Provisional score that doesn't factor in talent and will increase over time..
    </p>

    <div class="progress mx-auto mt-5 mb-5" data-value='70'>
        <span class="progress-left">
                      <span class="progress-bar border-primary"></span>
        </span>
        <span class="progress-right">
                      <span class="progress-bar border-danger"></span>
        </span>
        <div class="progress-value w-100 h-100 rounded-circle d-flex align-items-center justify-content-center">
          
          <div class="h2 font-weight-bold">73.4<sup class="small">%</sup></div>
        </div>
      </div>
</div>

src/Template/Artist/UserProfiles/thankyou.ctp
<div class="container thankupage">
    <div class="gray-strip">Your registration is complete.</div>
<p class="text-center mt-5">Congratulations! A Sound Check Live team member will contact you shortly for on-boarding. </p>
<div class="text-center mt-4 mb-4">
    <?php echo $this->Html->image('check-tick.png', ['alt' => 'tick']); ?>
</div>
    <!-- <p class="text-center mt-5">A Sound Check Live team Member will contact you shortly for on-boarding.</br>
        Your Sound Check live profile has generated a SCL Score of <?= $score ?>.</br>
        This is a provisional score that doesn't factor in talent and will increase over time.
    </p> -->
    <!-- <div class="progress mx-auto mt-5 mb-5" data-value='<?= $score ?>'>
        <span class="progress-left">
                      <span class="progress-bar border-primary"></span>
        </span>
        <span class="progress-right">
                      <span class="progress-bar border-primary"></span>
        </span>
        <div class="progress-value w-100 h-100 rounded-circle d-flex align-items-center justify-content-center">
          <div class="h2 font-weight-bold"><?= $score ?><sup class="small"></sup></div>
        </div>
      </div> -->
    <div class="text-center"><a href="/catalog">Click here for catalog</a></div>
</div>


<?php 
    echo $this->Html->script([
        'Artist/UserProfiles/redirect_to_music_page',
    ], [
        'block' => 'scriptBottom'
    ]); 
?>